name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.10, 3.11]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build
      run: |
        cd genshin_artifact_core
        maturin develop

    - name: Export install file
      if: github.ref == 'refs/heads/main'
      run: |
        cd genshin_artifact_core
        maturin build
        mv target/wheels/*.whl genshin_artifact_core-${{ matrix.python-version }}-${{ matrix.os }}.whl
      uses: actions/upload-artifact@v2
      with:
        name: genshin_artifact_core-${{ matrix.python-version }}-${{ matrix.os }}.whl
        path: genshin_artifact_core-${{ matrix.python-version }}-${{ matrix.os }}.whl
