name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.11']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create and start virtual environment
      run: |
        python3 -m venv venv

    - name: Install dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install maturin

    - name: Build
      run: |
        source venv/bin/activate
        cd python_genshin_artifact_core
        maturin develop

    - name: Export install file
      if: github.ref == 'refs/heads/main'
      run: |
        source venv/bin/activate
        cd python_genshin_artifact_core
        maturin build
        mv target/wheels/*.whl genshin_artifact_core-${{ matrix.python-version }}-${{ matrix.os }}.whl

    - name: Upload Artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v2
      with:
        name: genshin_artifact_core-${{ matrix.python-version }}-${{ matrix.os }}.whl
        path: python_genshin_artifact_core/genshin_artifact_core-${{ matrix.python-version }}-${{ matrix.os }}.whl
